export * from "./listActions"
export * from "./cardActions"

export const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  ADD_LIST: "ADD_LIST",
  GET_ALL_LIST: "GET_ALL_LIST",
  ERROR_LIST_MODULE: "ERROR_LIST_MODULE",
  DRAG_HAPPENED: "DRAG-HAPPENED",
  ERROR_TASK_MODULE: "ERROR_TASK_MODULE",
  GET_ALL_TASK: "GET_ALL_TASK",
  EDIT_CARD:"EDIT_CARD",
  DELETE_CARD:"DELETE_CARD",
}
